import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ReactQueryProvider from './components/ReactQueryProvider';
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
      <html lang="en">
        <body className="min-h-screen flex flex-col text-neutral-900 bg-white antialiased">
        <ReactQueryProvider>
          <Navbar />
          <main className="mt-6 relative flex-1 main-with-bg">
          <div
            className="absolute inset-0 -z-10 pointer-events-none"
            aria-hidden="true"
          >
            <div className="w-full h-full bg-[url('/bg.svg')] bg-center bg-cover" />
          </div>
            {children}
          <Footer year={2025} />
          </main>
        </ReactQueryProvider>
        </body>
      </html>
  );
} 